apiVersion: apps/v1
kind: Deployment
metadata:
  name: pharma-patient-app
  labels:
    app: pharma-patient-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: pharma-patient-app
  template:
    metadata:
      labels:
        app: pharma-patient-app
    spec:
      containers:
      - name: pharma-patient-app
        image: sibhanayak/pharma-patient-app:latest
        ports:
        - containerPort: 3000
