apiVersion: v1
kind: Service
metadata:
  name: pharma-patient-app-service
spec:
  type: NodePort
  ports:
  - name: http
    port: 3000
    targetPort: 3000
    protocol: TCP
  selector:
    app: pharma-patient-app
